### ISSUE TITLE
Integrate Additional Sqoop Commands

### ISSUE THREAD

**Issue by nishair** [lucafon/pysqoop#1]
It should be nice if we could incorporate these commands:
-Doraoop.import.partitions
--as-parquetfile
--direct

Let me know which places would be ideal to commit this code

**Comment by lucafon** [comment]
Hi Anish,

Since you've forked the repo, it would be good if you:
- commit and push your changes to your repo
- open a branch on my repo and push your changes on it
- crate a pull request to me

**Comment by nishair** [comment]
Sorry for the delay @lucafon . Been busy with putting out fire at work :p I have created a pull request. Will integrate the other two over the weekend
